let inputt = `STT -> MFP | 5
AIB -> ZGK | 6
ZGK -> KVX | 20
STT -> AFG | 4
AFG -> ZGK | 16
MFP -> BDD | 13
BDD -> AIB | 5
AXU -> MFP | 4
CLB -> BLV | 20
AIB -> BDD | 13
BLV -> AXU | 17
AFG -> CLB | 2`;

let input = `EYC -> IZI | 9
HCW -> ZUJ | 8
QKK -> QTT | 10
EGQ -> NMO | 6
OWH -> UVC | 9
MRN -> HAT | 16
OAM -> INR | 13
HZS -> DNC | 1
JOR -> OWH | 4
QTT -> SPA | 6
UVC -> QZO | 16
OAM -> XVE | 15
TRL -> VQJ | 16
HAT -> OKJ | 15
DKX -> BMO | 14
XVE -> ZNT | 17
EGQ -> OMA | 14
DNC -> UZJ | 15
VQJ -> QKK | 17
SHA -> JVJ | 7
DGV -> TRL | 9
JOR -> CVT | 1
LVJ -> CVT | 10
CVT -> HZS | 13
SPA -> OKJ | 20
QAE -> OAM | 13
NMO -> TJR | 20
TJR -> MRN | 10
QAE -> EIZ | 16
KGN -> EIZ | 9
IZI -> URD | 15
EIZ -> SHA | 7
URD -> DKX | 20
HAT -> TJR | 7
OKJ -> NMO | 20
SPA -> DKX | 16
ZUJ -> LVJ | 5
STT -> EYC | 7
BMO -> DGV | 3
ZNT -> DFR | 7
JVJ -> QAE | 1
MRN -> TJR | 16
UZJ -> INR | 9
LVJ -> HAT | 15
QRC -> EGQ | 16
OMA -> JOR | 14
HAT -> CYB | 16
DFR -> QRC | 5
CYB -> KGN | 8
QZO -> HCW | 4`;
